# Generated by Django 3.2.9 on 2021-11-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='имя покупателя')),
                ('last_name', models.CharField(max_length=30, verbose_name='фамилия покупателя')),
            ],
        ),
        migrations.RemoveField(
            model_name='shopinfo',
            name='number_of_buyers',
        ),
        migrations.RemoveField(
            model_name='shopinfo',
            name='number_of_purchases',
        ),
        migrations.RemoveField(
            model_name='shopinfo',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='description',
            field=models.CharField(default=1, max_length=50, verbose_name='описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=7, verbose_name='цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='title',
            field=models.CharField(default=1, max_length=30, verbose_name='имя товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='customers',
            field=models.ManyToManyField(related_name='customer_set', to='core.Customer'),
        ),
    ]
