# Generated by Django 3.2.9 on 2021-11-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_shopinfo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='customers',
            field=models.ManyToManyField(related_name='shopinfos', to='core.Customer', verbose_name='покупатели'),
        ),
    ]
