# Generated by Django 3.2.9 on 2021-11-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_shopinfo_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinfo',
            name='purchase_date',
            field=models.DateField(auto_now=True, verbose_name='дата покупки'),
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='purchase_time',
            field=models.TimeField(auto_now=True, verbose_name='время покупки'),
        ),
    ]
