# Generated by Django 3.2.9 on 2021-11-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211111_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopinfo',
            name='purchase_time',
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='purchase_date',
            field=models.DateTimeField(auto_now=True, verbose_name='дата покупки'),
        ),
    ]
