# Generated by Django 3.2.9 on 2021-11-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211111_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='purchase_date',
            field=models.DateField(verbose_name='дата покупки'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='purchase_time',
            field=models.TimeField(verbose_name='время покупки'),
        ),
    ]
